<br /><br />
<div id="view-content">
	<p><strong>Modulo de administrador</strong></p>
</div>

<?php if($this->paginator){?>
  <?=$this->paginator;?>
    <table>
        <tr>
            <th>Nombre</th>
            <th>Apellido</th>
        </tr>
        <?php foreach($this->paginator as $key => $row){ ?>
            <tr>
                <td><?=$row->nombre?></td>
                <td><?=$row->apellidos?></td>
            </tr>
        <?php } ?>
    </table>
    <?php echo $this->paginator; ?>
<?php }else{ ?>
No results.
<?php } ?>