
<?php
if ($this->pageCount){ ?>
<div class="paginationControl">
<!-- Previous page link -->
<?php if (isset($this->previous)){ ?>
  <a href="<?php echo $this->url(array('page' => $this->previous)); ?>">
    &lt; Previous
  </a> |
<?php }else{ ?>
  <span class="disabled">&lt; Previous</span> |
<?php } ?>
 
<!-- Numbered page links -->
<?php foreach ($this->pagesInRange as $page){ ?>
  <?php if ($page != $this->current){ ?>
    <a href="<?php echo $this->url(array('page' => $page)); ?>">
        <?php echo $page; ?>
    </a> |
  <?php }else{ ?>
    <span id="current_page"><?php echo $page; ?></span> |
  <?php } ?>
<?php } ?>
 
<!-- Next page link -->
<?php if (isset($this->next)){ ?>
  <a href="<?php echo $this->url(array('page' => $this->next)); ?>">
    Next &gt;
  </a>
<?php }else{ ?>
  <span class="disabled">Next &gt;</span>
<?php } ?>
</div>
<?php } ?>