<?php
echo $this->doctype('HTML5');
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
$this->headTitle()->setSeparator(' - ');
$this->headTitle('Scumbag Blues Music & Stuff');
?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="es" lang="es">
	<head>
		<?=$this->headMeta(); ?>
		<?=$this->headTitle(); ?>

		<link type="text/css" rel="stylesheet" href="<?= $this->baseUrl().'/css/bootstrap-responsive.css'?>" />
		<link type="text/css" rel="stylesheet" href="<?= $this->baseUrl().'/css/bootstrap.css'?>" />
		<link type="text/css" rel="stylesheet" href="<?= $this->baseUrl().'/css/base.css'?>" />
	</head>
	<body>
		<div class="navbar navbar-fixed-top">
      		<div class="navbar-inner">
        		<div class="container-fluid">
          			<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            			<span class="icon-bar"></span>
            			<span class="icon-bar"></span>
            			<span class="icon-bar"></span>
          			</a>
          			<!--  <a class="brand" href="#">Project name</a>-->
          			
          				<div class="nav-collapse">
            				<ul class="nav">
              					<li class="active"><a href="#">Home</a></li>
              					<li><a href="#about">About</a></li>
              					<li><a href="#contact">Contact</a></li>
            				</ul>
            				
            				<p class="navbar-text pull-right">Logged in as <a href="#">username</a></p>
            				<span class='title_shadow'>Titulo aquí</span>
          				</div><!--/.nav-collapse -->
          					
        		</div>
      		</div>
    	</div>
		<div class="container-fluid">
      		<div class="row-fluid">
        		<div class="span3">
          			<div class="well sidebar-nav">
            			<ul class="nav nav-list-scumbag">
			              <li class="nav-header">Sidebar</li>
			              <li class="active"><a href="#">Link</a></li>
			              <li><a href="#">Link</a></li>
			              <li><a href="#">Link</a></li>
			              <li><a href="#">Link</a></li>
			              <li class="nav-header">Sidebar</li>
			              <li><a href="#">Link</a></li>
			              <li><a href="#">Link</a></li>
			              <li><a href="#">Link</a></li>
			              <li><a href="#">Link</a></li>
			              <li><a href="#">Link</a></li>
			              <li><a href="#">Link</a></li>
			              <li class="nav-header">Sidebar</li>
			              <li><a href="#">Link</a></li>
			              <li><a href="#">Link</a></li>
			              <li><a href="#">Link</a></li>
            			</ul>
          			</div><!--/.well -->
        		</div><!--/span-->
        		<div class="span9">
		          <div class="hero-unit">
		            <h1>Hello, world!</h1>
						<?php echo $this->layout()->content; ?>
		            <p>This is a template for a simple marketing or informational website. It includes a large callout called the hero unit and three supporting pieces of content. Use it as a starting point to create something more unique.</p>
		            <p><a class="btn btn-primary-scumbag btn-large">Learn more &raquo;</a></p>
		          </div>
		          <div class="row-fluid">
		            <div class="span4">
		              <h2>Heading</h2>
		              <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
		              <p><a class="btn" href="#">View details &raquo;</a></p>
		            </div><!--/span-->
		            <div class="span4">
		              <h2>Heading</h2>
		              <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
		              <p><a class="btn" href="#">View details &raquo;</a></p>
		            </div><!--/span-->
		            <div class="span4">
		              <h2>Heading</h2>
		              <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
		              <p><a class="btn" href="#">View details &raquo;</a></p>
		            </div><!--/span-->
		          </div><!--/row-->
		          <div class="row-fluid">
		            <div class="span4">
		              <h2>Heading</h2>
		              <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
		              <p><a class="btn" href="#">View details &raquo;</a></p>
		            </div><!--/span-->
		            <div class="span4">
		              <h2>Heading</h2>
		              <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
		              <p><a class="btn" href="#">View details &raquo;</a></p>
		            </div><!--/span-->
		            <div class="span4">
		              <h2>Heading</h2>
		              <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
		              <p><a class="btn" href="#">View details &raquo;</a></p>
		            </div><!--/span-->
		          </div><!--/row-->
        		</div><!--/span-->
      		</div><!--/row-->
      		
     	 	<hr>
     	 	
	  		<footer>
        		<p>&copy; <a href='http://www.twitter.com/scumbagblues'>@scumbagblues 2012</a></p>
      		</footer>
    	</div>
	</body>
</html>
