<?php
echo $this->doctype('HTML5');
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
$this->headTitle()->setSeparator(' - ');
$this->headTitle('Scumbag Blues Music & Stuff');
$auth = Zend_Auth::getInstance();
?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="es" lang="es">
	<head>
		<?=$this->headMeta(); ?>
		<!-- Etiqueta para que el css se ahaga "responsive" y se ajuste al tamaño de la pantalla -->
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<?=$this->headTitle(); ?>
		<?=$this->jQuery();?>

		<link type="text/css" rel="stylesheet" href="<?= $this->baseUrl().'/css/bootstrap-responsive.css'?>" />
		<link type="text/css" rel="stylesheet" href="<?= $this->baseUrl().'/css/bootstrap.css'?>" />
		<link type="text/css" rel="stylesheet" href="<?= $this->baseUrl().'/css/base.css'?>" />
	</head>
	<body>
		<div class="navbar navbar-fixed-top">
      		<div class="navbar-inner">
        		<div class="container-fluid">
          			<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            			<span class="icon-bar"></span>
            			<span class="icon-bar"></span>
            			<span class="icon-bar"></span>
          			</a>
          			<!--  <a class="brand" href="#">Project name</a>-->
          			
          				<div class="nav-collapse">
            				<ul class="nav">
              				  <?php echo $this->menuPrincipal();?>
            				</ul>
            				<?php echo $this->sesionUsuario();?>
            				<span class='title_shadow'>SCUMBAG BLUES</span>
          				</div><!--/.nav-collapse -->
          					
        		</div>
      		</div>
    	</div>
		<div class="container-fluid">
      		<div class="row-fluid">
        		<div class="span3">
          			<div class="well sidebar-nav">
          			 <div>&nbsp;&nbsp;</div>
            			Algo aquí
							
          			</div><!--/.well -->
          			<div>
          				<script charset="utf-8" src="http://widgets.twimg.com/j/2/widget.js"></script>
							<script>
							new TWTR.Widget({
							  version: 2,
							  type: 'profile',
							  rpp: 4,
							  interval: 30000,
							  width: 250,
							  height: 300,
							  theme: {
							    shell: {
							      background: '#999999',
							      color: '#ffffff'
							    },
							    tweets: {
							      background: '#000000',
							      color: '#ffffff',
							      links: '#e33b3b'
							    }
							  },
							  features: {
							    scrollbar: false,
							    loop: false,
							    live: false,
							    behavior: 'all'
							  }
							}).render().setUser('scumbagblues').start();
							</script>
							<div>&nbsp;</div>
							<div>&nbsp;</div>
							<script>
							new TWTR.Widget({
							  version: 2,
							  type: 'search',
							  search: '@offspring',
							  interval: 30000,
							  title: 'The Offspring',
							  subject: '@offspring',
							  width: 250,
							  height: 300,
							  theme: {
							    shell: {
							      background: '#000000',
							      color: '#eb4444'
							    },
							    tweets: {
							      background: '#eaeaea',
							      color: '#e60909',
							      links: '#0079ad'
							    }
							  },
							  features: {
							    scrollbar: true,
							    loop: true,
							    live: true,
							    behavior: 'default'
							  }
							}).render().start();
							</script>
          			</div>
        		</div><!--/span-->
        		<div class="span9">
		          <div class="hero-unit">
		            <h1>Acceso a usuarios</h1>
		            	<div>&nbsp;</div>
		            	<?php if (!is_null($this->error_login)){?>
		            	<div class='alert-message error'><?php echo $this->error_login;?></div>
		            	<?php }?>
						<?php echo $this->layout()->content; ?>
		                <!--<p><a class="btn btn-primary-scumbag btn-large">Learn more &raquo;</a></p>-->
		          </div>
		          <h3>Recomendaciones</h3>
		          <div class="row-fluid">
		            <div class="span4">
		            	<div class='scumbag-box'>
		              		<h2>Heading</h2>
		              		<p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
		              		<p><a class="btn" href="#">View details &raquo;</a></p>
		            	</div>
		            </div><!--/span-->
		            <div class="span4">
		            	<div class='scumbag-box'>
			              <h2>Heading</h2>
			              <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
			              <p><a class="btn" href="#">View details &raquo;</a></p>
		              	</div>
		            </div><!--/span-->
		            <div class="span4">
		            	<div class='scumbag-box'>
			              <h2>Heading</h2>
			              <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
			              <p><a class="btn" href="#">View details &raquo;</a></p>
		              	</div>
		            </div><!--/span-->
		          </div><!--/row-->
		          <div class="row-fluid">
		            <div class="span4">
		            	<div class='scumbag-box'>
			              <h2>Heading</h2>
			              <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
			              <p><a class="btn" href="#">View details &raquo;</a></p>
		              	</div>
		            </div><!--/span-->
		            <div class="span4">
		            	<div class='scumbag-box'>
			              <h2>Heading</h2>
			              <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
			              <p><a class="btn" href="#">View details &raquo;</a></p>
		              	</div>
		            </div><!--/span-->
		            <div class="span4">
		            	<div class='scumbag-box'>
			              <h2>Heading</h2>
			              <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
			              <p><a class="btn" href="#">View details &raquo;</a></p>
			        	</div>
		            </div><!--/span-->
		          </div><!--/row-->
        		</div><!--/span-->
      		</div><!--/row-->
      		
     	 	<hr>
     	 	
	  		<footer>
        		<p>&copy; <a href='http://twitter.com/scumbagblues'>@scumbagblues <?php echo date('Y');?></a></p>
      		</footer>
    	</div>
	</body>
</html>
